export interface Product {
  id: string;
  name: string;
  price: number;
  image: string;
  category: string;
  description: string;
  co2Saved: number;
  isEco: boolean;
  condition: 'new' | 'like-new' | 'refurbished';
  rating: number;
  reviews: Review[];
  ingredients?: string[];
  materials?: string[];
  sustainability: string;
  originalPrice?: number;
  unit?: string;
}

export interface Review {
  id: string;
  author: string;
  rating: number;
  date: string;
  comment: string;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Cotton Tote Bag',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1621357366416-3e754e1a3d8b?w=600',
    category: 'Eco Home',
    description: 'Durable, reusable tote bag made from 100% organic cotton. Perfect for groceries, beach trips, or everyday use.',
    co2Saved: 2.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [
      {
        id: 'r1',
        author: 'Sarah M.',
        rating: 5,
        date: '2024-11-15',
        comment: 'Love this bag! Super sturdy and spacious.'
      },
      {
        id: 'r2',
        author: 'John D.',
        rating: 4,
        date: '2024-11-10',
        comment: 'Great quality, helps me reduce plastic use.'
      }
    ],
    materials: ['100% Organic Cotton', 'Natural Dyes', 'Recycled Thread'],
    sustainability: 'Replaces 500+ single-use plastic bags. Made in fair-trade facilities.',
    originalPrice: 29.99,
    unit: '1 pc'
  },
  {
    id: '2',
    name: 'Bamboo Toothbrush Set',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1592372554345-22ced975691d?w=600',
    category: 'Skincare',
    description: 'Set of 4 biodegradable bamboo toothbrushes with soft, BPA-free bristles.',
    co2Saved: 1.2,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [
      {
        id: 'r3',
        author: 'Emma L.',
        rating: 5,
        date: '2024-11-20',
        comment: 'Perfect! My whole family switched to these.'
      }
    ],
    materials: ['Sustainable Bamboo', 'BPA-Free Nylon Bristles'],
    sustainability: 'Replaces plastic toothbrushes that take 400+ years to decompose. Fully biodegradable handle.',
    originalPrice: 15.99,
    unit: '4 pack'
  },
  {
    id: '3',
    name: 'Solar-Powered Phone Charger',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1739268984311-b478fccf256e?w=600',
    category: 'Green Gadgets',
    description: 'Portable solar charger with dual USB ports. Perfect for camping or emergency backup.',
    co2Saved: 5.8,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [
      {
        id: 'r4',
        author: 'Mike R.',
        rating: 5,
        date: '2024-11-18',
        comment: 'Works great! Charged my phone fully in direct sunlight.'
      }
    ],
    materials: ['Monocrystalline Solar Panels', 'Recycled Plastic Housing'],
    sustainability: 'Generates clean energy. Reduces reliance on grid electricity from fossil fuels.',
    originalPrice: 65.00,
    unit: '1 device'
  },
  {
    id: '4',
    name: 'Recycled Glass Water Bottle',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1649254762645-9b011f1196b0?w=600',
    category: 'Recycled Items',
    description: 'Beautiful water bottle made from 100% recycled glass with bamboo lid.',
    co2Saved: 3.2,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['100% Recycled Glass', 'Bamboo Lid', 'Silicone Seal'],
    sustainability: 'Saves 1000+ single-use plastic bottles per year. Made from post-consumer recycled glass.',
    originalPrice: 24.99,
    unit: '500 ml'
  },
  {
    id: '5',
    name: 'Organic Green Tea - 50 Bags',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1585849835117-1446a1514ea6?w=600',
    category: 'Organic Food',
    description: 'Premium organic green tea leaves in compostable tea bags. Rich in antioxidants.',
    co2Saved: 0.8,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [
      {
        id: 'r5',
        author: 'Lisa K.',
        rating: 5,
        date: '2024-11-22',
        comment: 'Best green tea I have ever had! Smooth and delicious.'
      }
    ],
    ingredients: ['Organic Green Tea Leaves', 'Natural Bergamot Oil'],
    sustainability: 'Compostable packaging and tea bags. Organic farming reduces pesticide use by 100%.'
  },
  {
    id: '6',
    name: 'Natural Beeswax Wraps',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1632142334452-7efccdbf9a1d?w=600',
    category: 'Eco Home',
    description: 'Set of 3 reusable food wraps made with organic cotton and beeswax. Alternative to plastic wrap.',
    co2Saved: 2.1,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Organic Cotton', 'Natural Beeswax', 'Jojoba Oil', 'Tree Resin'],
    sustainability: 'Reusable for up to 1 year. Replaces 1000+ feet of plastic wrap.'
  },
  {
    id: '7',
    name: 'Lavender Essential Oil',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1647934174400-caf502df3f7b?w=600',
    category: 'Skincare',
    description: 'Pure, organic lavender essential oil. Perfect for aromatherapy and skincare.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 5.0,
    reviews: [
      {
        id: 'r6',
        author: 'Rachel W.',
        rating: 5,
        date: '2024-11-19',
        comment: 'Smells amazing! Helps me relax before bed.'
      }
    ],
    ingredients: ['100% Pure Lavender Essential Oil'],
    sustainability: 'Sustainably harvested. Glass packaging is recyclable.'
  },
  {
    id: '8',
    name: 'Compostable Phone Case',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1676337168330-552471162128?w=600',
    category: 'Green Gadgets',
    description: 'Protective phone case made from plant-based materials. Fully compostable.',
    co2Saved: 1.9,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Plant-Based Bioplastic', 'Flax Straw', 'Natural Pigments'],
    sustainability: 'Decomposes in 6 months in composting conditions. No harmful plastics.'
  },
  {
    id: '9',
    name: 'Refurbished Wireless Earbuds',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1627989580309-bfaf3e58af6f?w=600',
    category: 'Recycled Items',
    description: 'High-quality refurbished wireless earbuds with excellent sound quality.',
    co2Saved: 8.5,
    isEco: true,
    condition: 'refurbished',
    rating: 4.4,
    reviews: [],
    materials: ['Refurbished Electronics'],
    sustainability: 'Refurbishing electronics saves 85% of CO₂ compared to manufacturing new ones.'
  },
  {
    id: '10',
    name: 'Organic Quinoa - 2lb',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1671058844328-fecbd3d61dc0?w=600',
    category: 'Organic Food',
    description: 'Premium organic quinoa, high in protein and naturally gluten-free.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    ingredients: ['Organic White Quinoa'],
    sustainability: 'Organic farming methods. Recyclable packaging.'
  },
  {
    id: '11',
    name: 'Natural Face Moisturizer',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1763503834047-ac85c4105c0b?w=600',
    category: 'Skincare',
    description: 'Hydrating face cream with organic ingredients. Suitable for all skin types.',
    co2Saved: 0.9,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [
      {
        id: 'r7',
        author: 'Amanda P.',
        rating: 5,
        date: '2024-11-21',
        comment: 'My skin has never felt better! No harsh chemicals.'
      }
    ],
    ingredients: ['Organic Shea Butter', 'Jojoba Oil', 'Aloe Vera', 'Vitamin E'],
    sustainability: 'Cruelty-free. Glass packaging. No synthetic fragrances or parabens.'
  },
  {
    id: '12',
    name: 'LED Smart Bulb - 4 Pack',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1752391702044-b3c75fde78bd?w=600',
    category: 'Green Gadgets',
    description: 'Energy-efficient LED bulbs with smart controls. Save up to 80% on energy costs.',
    co2Saved: 12.4,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['LED Components', 'Recyclable Aluminum'],
    sustainability: 'Uses 80% less energy than incandescent bulbs. Lasts 25x longer.'
  },
  {
    id: '13',
    name: 'Bamboo Cutlery Set',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1674676043851-dfb5553afa8a?w=600',
    category: 'Eco Home',
    description: 'Portable bamboo cutlery set with pouch. Ideal for zero-waste lunches.',
    co2Saved: 1.8,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Sustainable Bamboo', 'Cotton Pouch'],
    sustainability: 'Compostable and reusable. Replaces single-use plastic cutlery.'
  },
  {
    id: '14',
    name: 'Mineral Sunscreen SPF 50',
    price: 25.50,
    image: 'https://images.unsplash.com/photo-1698664434322-94a43b98b9ba?w=600',
    category: 'Skincare',
    description: 'Reef-safe mineral sunscreen. Water-resistant and gentle on skin.',
    co2Saved: 0.7,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Zinc Oxide', 'Coconut Oil', 'Shea Butter'],
    sustainability: 'Reef-safe formula. Recyclable aluminum bottle.'
  },
  {
    id: '15',
    name: 'Water Powered Clock',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1734024653249-c6ba7b742ad2?w=600',
    category: 'Green Gadgets',
    description: 'Unique clock powered by water and salt. No batteries required.',
    co2Saved: 4.2,
    isEco: true,
    condition: 'new',
    rating: 4.3,
    reviews: [],
    materials: ['Recycled Plastic', 'Copper/Zinc Electrodes'],
    sustainability: 'Eliminates battery waste. Runs for weeks on a single fill.'
  },
  {
    id: '16',
    name: 'Recycled Paper Notebook',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1625533617580-3977f2651fc0?w=600',
    category: 'Recycled Items',
    description: 'A5 notebook with pages made from 100% recycled paper.',
    co2Saved: 1.1,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['100% Recycled Paper', 'Cardboard Cover'],
    sustainability: 'Saves trees and water compared to virgin paper production.'
  },
  {
    id: '17',
    name: 'Upcycled Denim Tote',
    price: 35.00,
    image: 'https://images.unsplash.com/photo-1683148754073-cfa906017a10?w=600',
    category: 'Recycled Items',
    description: 'Stylish tote bag handmade from upcycled denim jeans.',
    co2Saved: 6.5,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Upcycled Denim', 'Cotton Lining'],
    sustainability: 'Diverts textile waste from landfills. Reduces demand for new cotton.'
  },
  {
    id: '18',
    name: 'Organic Coffee Beans',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1677443144837-e80ccaa9555f?w=600',
    category: 'Organic Food',
    description: 'Fair-trade organic coffee beans. Rich, dark roast.',
    co2Saved: 2.0,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['100% Organic Arabica Beans'],
    sustainability: 'Shade-grown to preserve biodiversity. Compostable bag.'
  },
  {
    id: '19',
    name: 'Raw Organic Honey',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1580568183078-5f3464ac07e7?w=600',
    category: 'Organic Food',
    description: 'Unfiltered raw honey from wildflower meadows.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 5.0,
    reviews: [],
    ingredients: ['Raw Honey'],
    sustainability: 'Supports pollinator populations. Glass jar is infinitely recyclable.'
  },
  {
    id: '20',
    name: 'Biodegradable Trash Bags',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1605933353319-31ea576f2d24?w=600',
    category: 'Eco Home',
    description: 'Compostable trash bags made from plant starches.',
    co2Saved: 3.0,
    isEco: true,
    condition: 'new',
    rating: 4.4,
    reviews: [],
    materials: ['Plant Starch', 'Vegetable Oils'],
    sustainability: 'Breaks down completely in industrial composting facilities.'
  },
  // Eco Home Additions
  {
    id: '21',
    name: 'Biodegradable Sponges (3-Pack)',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1598998267982-d2a80038fd0b?w=600',
    category: 'Eco Home',
    description: 'Plastic-free sponges made from coconut fiber and wood cellulose.',
    co2Saved: 0.8,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Coconut Fiber', 'Wood Cellulose'],
    sustainability: '100% compostable. No microplastics.'
  },
  {
    id: '22',
    name: 'Amber Glass Spray Bottle',
    price: 14.50,
    image: 'https://images.unsplash.com/photo-1698593975771-f7b38d49664f?w=600',
    category: 'Eco Home',
    description: 'Refillable amber glass bottle with durable trigger sprayer.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Recycled Glass', 'BPA-free Plastic Nozzle'],
    sustainability: 'Eliminates single-use plastic bottles.'
  },
  {
    id: '23',
    name: 'Coconut Bowl Set',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1629705744513-03b66a5b043d?w=600',
    category: 'Eco Home',
    description: 'Handcrafted bowls made from reclaimed coconut shells.',
    co2Saved: 2.2,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Coconut Shell', 'Coconut Oil Polish'],
    sustainability: 'Upcycled agricultural waste product.'
  },
  {
    id: '24',
    name: 'Mesh Produce Bags',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1634640910682-fbeb74cfa1a2?w=600',
    category: 'Eco Home',
    description: 'Set of 5 reusable mesh bags for fruit and vegetables.',
    co2Saved: 1.9,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Organic Cotton Mesh'],
    sustainability: 'Replaces hundreds of plastic produce bags.'
  },
  {
    id: '25',
    name: 'Wool Dryer Balls',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1690583368332-c1931e70e53e?w=600',
    category: 'Eco Home',
    description: 'Natural fabric softener alternative that reduces drying time.',
    co2Saved: 10.5, // High saving due to energy reduction
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['100% New Zealand Wool'],
    sustainability: 'Reduces dryer energy usage by up to 25%.'
  },
  {
    id: '26',
    name: 'Countertop Compost Bin',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1684324278460-25fbb2e3f175?w=600',
    category: 'Eco Home',
    description: 'Stylish stainless steel bin with charcoal filter for odor control.',
    co2Saved: 45.0, // Potential saving from composting
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Stainless Steel', 'Activated Charcoal'],
    sustainability: 'Facilitates food waste composting, reducing landfill methane.'
  },
  {
    id: '27',
    name: 'Bamboo Toilet Paper - 12 Rolls',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1756728207514-d254facc9fb2?w=600',
    category: 'Eco Home',
    description: 'Tree-free toilet paper made from sustainably sourced bamboo.',
    co2Saved: 3.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['100% Bamboo Pulp'],
    sustainability: 'Saves trees. Bamboo grows 30x faster than trees.'
  },
  {
    id: '28',
    name: 'Silicone Food Lids',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1727021024931-90c226e8448d?w=600',
    category: 'Eco Home',
    description: 'Stretchy silicone lids in various sizes to fit any bowl or cup.',
    co2Saved: 2.0,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Food-grade Silicone'],
    sustainability: 'Replaces single-use plastic wrap and aluminum foil.'
  },
  {
    id: '29',
    name: 'Organic Cotton Sheet Set',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1639690222869-1e608aa51f82?w=600',
    category: 'Eco Home',
    description: 'Luxuriously soft sheets made from GOTS certified organic cotton.',
    co2Saved: 12.0,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Organic Cotton'],
    sustainability: 'Grown without harmful pesticides or synthetic fertilizers.'
  },
  {
    id: '30',
    name: 'Hemp Shower Curtain',
    price: 45.00,
    image: 'https://images.unsplash.com/photo-1608768390181-dda1b3455107?w=600',
    category: 'Eco Home',
    description: 'Natural, mold-resistant shower curtain made from durable hemp fabric.',
    co2Saved: 3.8,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['100% Hemp Canvas'],
    sustainability: 'Biodegradable alternative to PVC vinyl curtains.'
  },
  {
    id: '31',
    name: 'Laundry Detergent Sheets',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1714058957722-06d4f925dd39?w=600',
    category: 'Eco Home',
    description: 'Plastic-free laundry detergent strips. Dissolves completely in water.',
    co2Saved: 5.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Plant-based Surfactants'],
    sustainability: 'Zero-waste packaging. 90% lighter than liquid detergent, reducing transport emissions.'
  },
  {
    id: '32',
    name: 'Silicone Baking Mat',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1751776491855-c1e94cc0d43d?w=600',
    category: 'Eco Home',
    description: 'Non-stick baking mat that replaces parchment paper and foil.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Silicone', 'Fiberglass'],
    sustainability: 'Reusable thousands of times. Eliminates kitchen paper waste.'
  },
  // Skincare Additions
  {
    id: '33',
    name: 'Solid Shampoo Bar',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1608623676098-c52439068319?w=600',
    category: 'Skincare',
    description: 'Concentrated shampoo bar with essential oils. Plastic-free.',
    co2Saved: 0.6,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    ingredients: ['Coconut Oil', 'Argan Oil', 'Essential Oils'],
    sustainability: 'Replaces 2-3 plastic shampoo bottles.'
  },
  {
    id: '34',
    name: 'Solid Conditioner Bar',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1616367157213-d7ee3548263d?w=600',
    category: 'Skincare',
    description: 'Moisturizing conditioner bar for soft, shiny hair.',
    co2Saved: 0.6,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    ingredients: ['Cocoa Butter', 'Jojoba Oil', 'Vitamin B5'],
    sustainability: 'Zero-waste packaging. Long-lasting formula.'
  },
  {
    id: '35',
    name: 'Bamboo Cotton Swabs',
    price: 6.99,
    image: 'https://images.unsplash.com/photo-1643185720431-9c050eebbc9a?w=600',
    category: 'Skincare',
    description: 'Biodegradable cotton swabs with bamboo stems.',
    co2Saved: 0.3,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Bamboo', 'Organic Cotton'],
    sustainability: '100% compostable. Replaces plastic-stemmed swabs.'
  },
  {
    id: '36',
    name: 'Konjac Facial Sponge',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1665290051839-61303eb07c67?w=600',
    category: 'Skincare',
    description: 'Gentle exfoliating sponge made from konjac root fiber.',
    co2Saved: 0.2,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['100% Konjac Root'],
    sustainability: 'Fully biodegradable and compostable.'
  },
  {
    id: '37',
    name: 'Organic Body Butter',
    price: 28.00,
    image: 'https://images.unsplash.com/photo-1763446589903-3ff2e06b2c6e?w=600',
    category: 'Skincare',
    description: 'Rich, whipped body butter for deep hydration.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    ingredients: ['Shea Butter', 'Cocoa Butter', 'Almond Oil'],
    sustainability: 'Glass jar packaging. Organic ingredients.'
  },
  {
    id: '38',
    name: 'Natural Deodorant Stick',
    price: 14.00,
    image: 'https://images.unsplash.com/photo-1636708112636-546f80cf7094?w=600',
    category: 'Skincare',
    description: 'Aluminum-free deodorant in compostable cardboard tube.',
    co2Saved: 0.4,
    isEco: true,
    condition: 'new',
    rating: 4.4,
    reviews: [],
    ingredients: ['Arrowroot Powder', 'Coconut Oil', 'Essential Oils'],
    sustainability: 'Plastic-free packaging. Chemical-free formula.'
  },
  {
    id: '39',
    name: 'Rose Water Toner',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1517366359321-dfc55669f7f0?w=600',
    category: 'Skincare',
    description: 'Refreshing facial toner distilled from organic rose petals.',
    co2Saved: 0.3,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Organic Rose Distillate'],
    sustainability: 'Recyclable glass bottle. Sustainably sourced roses.'
  },
  {
    id: '40',
    name: 'Reusable Makeup Pads',
    price: 16.50,
    image: 'https://images.unsplash.com/photo-1588959570984-9f1e0e9a91a6?w=600',
    category: 'Skincare',
    description: 'Soft bamboo velour pads for removing makeup. Machine washable.',
    co2Saved: 4.0,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Bamboo Fiber', 'Cotton'],
    sustainability: 'Replaces thousands of disposable cotton rounds.'
  },
  {
    id: '41',
    name: 'Vegan Lip Balm',
    price: 5.99,
    image: 'https://images.unsplash.com/photo-1650531975416-30c7b43691a6?w=600',
    category: 'Skincare',
    description: 'Hydrating lip balm with plant waxes and oils.',
    co2Saved: 0.1,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    ingredients: ['Candelilla Wax', 'Coconut Oil', 'Vitamin E'],
    sustainability: 'Cruelty-free and vegan. Compostable tube.'
  },
  {
    id: '42',
    name: 'Coffee Body Scrub',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1677769237703-629d082d89bb?w=600',
    category: 'Skincare',
    description: 'Exfoliating body scrub made from repurposed coffee grounds.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Repurposed Coffee Grounds', 'Sugar', 'Coconut Oil'],
    sustainability: 'Upcycles coffee waste. Reduces landfill contribution.'
  },
  {
    id: '43',
    name: 'Tea Tree Face Wash',
    price: 24.00,
    image: 'https://images.unsplash.com/photo-1561095463-f9c0487824f1?w=600',
    category: 'Skincare',
    description: 'Clarifying gel cleanser for blemish-prone skin.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    ingredients: ['Tea Tree Oil', 'Aloe Vera', 'Willow Bark Extract'],
    sustainability: 'Biodegradable formula. Glass pump bottle.'
  },
  {
    id: '44',
    name: 'Wooden Hair Brush',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1747398690600-ffe8ecda9df1?w=600',
    category: 'Skincare',
    description: 'Anti-static hair brush with wooden bristles and handle.',
    co2Saved: 0.8,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Bamboo/Beech Wood', 'Natural Rubber'],
    sustainability: 'Durable alternative to plastic brushes. Compostable at end of life.'
  },
  // Green Gadgets Additions
  {
    id: '45',
    name: 'Solar Power Bank 20000mAh',
    price: 59.99,
    image: 'https://images.unsplash.com/photo-1720610784599-18c02b1cc9ee?w=600',
    category: 'Green Gadgets',
    description: 'High-capacity power bank with solar charging capability.',
    co2Saved: 6.5,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Recycled Plastic Casing', 'Lithium Polymer Battery'],
    sustainability: 'Harnesses renewable solar energy for mobile charging.'
  },
  {
    id: '46',
    name: 'Emergency Wind-Up Radio',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1645391986480-7c13dde82793?w=600',
    category: 'Green Gadgets',
    description: 'AM/FM radio with hand crank and solar charging. Includes flashlight.',
    co2Saved: 3.0,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Durable Plastic', 'Dynamo Generator'],
    sustainability: 'No batteries required. Reliable renewable power.'
  },
  {
    id: '47',
    name: 'Smart Thermostat',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=600',
    category: 'Green Gadgets',
    description: 'WiFi-enabled thermostat that optimizes heating and cooling.',
    co2Saved: 150.0, // Significant annual savings
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Glass', 'Recycled Electronics'],
    sustainability: 'Reduces HVAC energy consumption by up to 20%.'
  },
  {
    id: '48',
    name: 'Rechargeable Batteries AA (8-Pack)',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1706166987972-5c772443f29a?w=600',
    category: 'Green Gadgets',
    description: 'High-capacity NiMH rechargeable batteries.',
    co2Saved: 15.0,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Nickel-Metal Hydride'],
    sustainability: 'One rechargeable battery replaces hundreds of single-use alkalines.'
  },
  {
    id: '49',
    name: 'Smart Energy Monitor Plug',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1763543033943-d5c2ff70aadd?w=600',
    category: 'Green Gadgets',
    description: 'Monitor appliance energy usage via smartphone app.',
    co2Saved: 25.0,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Fire-retardant PC'],
    sustainability: 'Helps identify and reduce energy vampires.'
  },
  {
    id: '50',
    name: 'Solar Garden Lights (6-Pack)',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1698553497889-704f27f3d170?w=600',
    category: 'Green Gadgets',
    description: 'Waterproof LED path lights powered by the sun.',
    co2Saved: 18.0,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Stainless Steel', 'Glass'],
    sustainability: 'Zero electricity costs. Automatic dusk-to-dawn operation.'
  },
  {
    id: '51',
    name: 'Hand-Crank Flashlight',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1704648236426-e672ff74d655?w=600',
    category: 'Green Gadgets',
    description: 'Compact LED flashlight powered by winding.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.4,
    reviews: [],
    materials: ['ABS Plastic'],
    sustainability: 'Eliminates battery waste forever.'
  },
  {
    id: '52',
    name: 'Water Leak Sensor',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1702386102154-9eb38507aa2a?w=600',
    category: 'Green Gadgets',
    description: 'Smart sensor that alerts you to leaks instantly.',
    co2Saved: 5.0, // Indirect saving via water conservation/damage prevention
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Recycled Plastic Housing'],
    sustainability: 'Prevents water wastage and water damage.'
  },
  {
    id: '53',
    name: 'Smart Irrigation Controller',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1738598665698-7fd7af4b5e0c?w=600',
    category: 'Green Gadgets',
    description: 'Weather-aware sprinkler controller to save water.',
    co2Saved: 10.0, // Water processing energy savings
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Weather-resistant Plastic'],
    sustainability: 'Reduces outdoor water usage by up to 50%.'
  },
  {
    id: '54',
    name: 'Solar Bluetooth Speaker',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1594991523303-a54f2722dc3c?w=600',
    category: 'Green Gadgets',
    description: 'Portable speaker that charges while you play music outdoors.',
    co2Saved: 2.5,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Bamboo', 'Recycled Fabric'],
    sustainability: 'Renewable energy powered entertainment.'
  },
  {
    id: '55',
    name: 'Eco-Felt Laptop Sleeve',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1660578008459-3604f6c883c9?w=600',
    category: 'Green Gadgets',
    description: 'Protective sleeve made from recycled plastic bottles (rPET felt).',
    co2Saved: 1.8,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['rPET Felt'],
    sustainability: 'Diverts plastic bottles from oceans and landfills.'
  },
  {
    id: '56',
    name: 'Wooden Phone Stand',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1761311985262-d0a342290b56?w=600',
    category: 'Green Gadgets',
    description: 'Minimalist phone stand carved from sustainable wood.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Walnut Wood'],
    sustainability: 'Natural, biodegradable alternative to plastic stands.'
  },
  // Recycled Items Additions
  {
    id: '57',
    name: 'Recycled Polyester Backpack',
    price: 45.00,
    image: 'https://images.unsplash.com/photo-1540394285875-f7b4538c4874?w=600',
    category: 'Recycled Items',
    description: 'Rugged backpack made from 100% recycled plastic bottles.',
    co2Saved: 3.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['600D Recycled Polyester'],
    sustainability: 'Uses 50% less energy to produce than virgin polyester.'
  },
  {
    id: '58',
    name: 'Recycled Leather Journal',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1583341655648-78bdf4ed6d13?w=600',
    category: 'Recycled Items',
    description: 'Notebook bound in bonded recycled leather scraps.',
    co2Saved: 2.1,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Recycled Leather', 'Recycled Paper'],
    sustainability: 'Reduces waste from the leather industry.'
  },
  {
    id: '59',
    name: 'Recycled Plastic Outdoor Rug',
    price: 55.00,
    image: 'https://images.unsplash.com/photo-1743656642032-98512183602a?w=600',
    category: 'Recycled Items',
    description: 'Weather-resistant rug woven from recycled plastic straws.',
    co2Saved: 8.0,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Recycled Polypropylene'],
    sustainability: 'Durable and stain-resistant. Keeps plastic out of nature.'
  },
  {
    id: '60',
    name: 'Tire Planter',
    price: 35.00,
    image: 'https://images.unsplash.com/photo-1502708131121-0d759be5eadb?w=600',
    category: 'Recycled Items',
    description: 'Durable garden planter made from recycled rubber tires.',
    co2Saved: 12.0,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Recycled Rubber Tires'],
    sustainability: 'Extremely long-lasting. Diverts tires from landfills.'
  },
  {
    id: '61',
    name: 'Recycled Glass Vase',
    price: 28.99,
    image: 'https://images.unsplash.com/photo-1618441079655-28413f13113d?w=600',
    category: 'Recycled Items',
    description: 'Artisan blown vase crafted from crushed recycled glass.',
    co2Saved: 2.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['100% Recycled Glass'],
    sustainability: 'Melting recycled glass uses less energy than raw materials.'
  },
  {
    id: '62',
    name: 'Ocean Plastic Sunglasses',
    price: 75.00,
    image: 'https://images.unsplash.com/photo-1738104955869-e32946fbd893?w=600',
    category: 'Recycled Items',
    description: 'Stylish frames made from intercepted ocean plastics.',
    co2Saved: 1.2,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Ocean-bound Plastic', 'Polarized Lenses'],
    sustainability: 'Directly supports ocean cleanup efforts.'
  },
  {
    id: '63',
    name: 'Climbing Rope Dog Leash',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1744291139908-7154de3389c0?w=600',
    category: 'Recycled Items',
    description: 'Heavy-duty leash upcycled from retired climbing ropes.',
    co2Saved: 2.8,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Upcycled Nylon Rope'],
    sustainability: 'Gives a second life to non-recyclable safety gear.'
  },
  {
    id: '64',
    name: 'Recycled Aluminum Pen',
    price: 12.00,
    image: 'https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?w=600',
    category: 'Recycled Items',
    description: 'Sleek pen machined from recycled aluminum cans.',
    co2Saved: 0.5,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Recycled Aluminum'],
    sustainability: 'Infinitely recyclable material.'
  },
  {
    id: '65',
    name: 'Cork Yoga Mat',
    price: 65.00,
    image: 'https://images.unsplash.com/photo-1758599879795-536d5f203de9?w=600',
    category: 'Recycled Items',
    description: 'Non-slip yoga mat with recycled cork surface and rubber base.',
    co2Saved: 3.2,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Recycled Cork', 'Natural Rubber'],
    sustainability: 'Sustainable harvesting. Natural antimicrobial properties.'
  },
  {
    id: '66',
    name: 'Sailcloth Tote Bag',
    price: 55.00,
    image: 'https://images.unsplash.com/photo-1542957057-debadce4ce81?w=600',
    category: 'Recycled Items',
    description: 'Water-resistant tote made from retired boat sails.',
    co2Saved: 4.5,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Upcycled Sailcloth', 'Marine Rope'],
    sustainability: 'Unique, durable material diverted from landfill.'
  },
  {
    id: '67',
    name: 'Cardboard Stool',
    price: 25.00,
    image: 'https://images.unsplash.com/photo-1589420847301-caf51d62a5d1?w=600',
    category: 'Recycled Items',
    description: 'Surprisingly strong foldable stool made from recycled cardboard.',
    co2Saved: 5.0,
    isEco: true,
    condition: 'new',
    rating: 4.4,
    reviews: [],
    materials: ['Heavy-duty Recycled Cardboard'],
    sustainability: '100% recyclable and compostable furniture.'
  },
  {
    id: '68',
    name: 'Recycled Fleece Jacket',
    price: 89.00,
    image: 'https://images.unsplash.com/photo-1736427916729-b267aae5f962?w=600',
    category: 'Recycled Items',
    description: 'Warm fleece jacket made entirely from post-consumer plastic.',
    co2Saved: 6.0,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['100% Recycled Polyester'],
    sustainability: 'Keeps you warm while cleaning up the planet.'
  },
  // Organic Food Additions
  {
    id: '69',
    name: 'Organic Almond Butter',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1651794560385-6f22fe7950e5?w=600',
    category: 'Organic Food',
    description: 'Creamy, roasted almond butter with no added sugar or oil.',
    co2Saved: 1.1,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    ingredients: ['Organic Roasted Almonds'],
    sustainability: 'Bee-friendly farming practices. Glass jar.'
  },
  {
    id: '70',
    name: 'Fair Trade Dark Chocolate',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1646168932800-e48f378d37bb?w=600',
    category: 'Organic Food',
    description: '70% dark chocolate bar with sea salt.',
    co2Saved: 0.4,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Organic Cocoa Mass', 'Cane Sugar', 'Cocoa Butter'],
    sustainability: 'Fair Trade Certified. Supports sustainable cocoa farming.'
  },
  {
    id: '71',
    name: 'Organic Chia Seeds',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1610450624105-58a2f25f7911?w=600',
    category: 'Organic Food',
    description: 'Nutrient-dense superfood seeds rich in Omega-3s.',
    co2Saved: 0.9,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    ingredients: ['Organic Chia Seeds'],
    sustainability: 'Sustainably grown. Compostable pouch.'
  },
  {
    id: '72',
    name: 'Dried Mango Slices',
    price: 13.50,
    image: 'https://images.unsplash.com/photo-1760533535534-c69f637df2e6?w=600',
    category: 'Organic Food',
    description: 'Naturally sweet dried mango with no preservatives.',
    co2Saved: 0.7,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Organic Mango'],
    sustainability: 'Direct trade. Reduces food waste from ugly fruit.'
  },
  {
    id: '73',
    name: 'Organic Maple Syrup',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1758640927926-9f0b1cda712e?w=600',
    category: 'Organic Food',
    description: 'Grade A Amber rich taste maple syrup.',
    co2Saved: 1.2,
    isEco: true,
    condition: 'new',
    rating: 5.0,
    reviews: [],
    ingredients: ['100% Pure Organic Maple Syrup'],
    sustainability: 'Supports forest conservation. Glass bottle.'
  },
  {
    id: '74',
    name: 'Matcha Green Tea Powder',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1758186169087-b2fc139500f3?w=600',
    category: 'Organic Food',
    description: 'Ceremonial grade organic matcha from Japan.',
    co2Saved: 1.0,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    ingredients: ['Organic Matcha Green Tea'],
    sustainability: 'Shade-grown. Recyclable tin.'
  },
  {
    id: '75',
    name: 'Organic Rolled Oats',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1581864353082-f4d5afe4e21d?w=600',
    category: 'Organic Food',
    description: 'Gluten-free old fashioned oats for the perfect breakfast.',
    co2Saved: 0.6,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    ingredients: ['Organic Whole Grain Oats'],
    sustainability: 'Crop rotation farming improves soil health.'
  },
  {
    id: '76',
    name: 'Vegan Protein Powder',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1622818426027-8909055faae8?w=600',
    category: 'Organic Food',
    description: 'Plant-based protein blend (Pea, Brown Rice, Hemp).',
    co2Saved: 2.5,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    ingredients: ['Organic Pea Protein', 'Organic Cocoa'],
    sustainability: 'Much lower carbon footprint than whey protein.'
  },
  {
    id: '77',
    name: 'Virgin Coconut Oil',
    price: 14.50,
    image: 'https://images.unsplash.com/photo-1628602040839-682c1c959aac?w=600',
    category: 'Organic Food',
    description: 'Cold-pressed, unrefined coconut oil for cooking or beauty.',
    co2Saved: 1.3,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Organic Coconut Oil'],
    sustainability: 'Fair trade certified. Glass jar.'
  },
  {
    id: '78',
    name: 'Organic Turmeric Powder',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1619367300933-376d8c5cd5f9?w=600',
    category: 'Organic Food',
    description: 'High-curcumin turmeric powder for cooking and wellness.',
    co2Saved: 0.4,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    ingredients: ['Organic Turmeric Root'],
    sustainability: 'Supports small-scale spice farmers.'
  },
  {
    id: '79',
    name: 'Artisan Granola',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1645517976245-569a91016f79?w=600',
    category: 'Organic Food',
    description: 'Small-batch granola with nuts, seeds, and dried fruit.',
    co2Saved: 0.8,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    ingredients: ['Oats', 'Maple Syrup', 'Pecans'],
    sustainability: 'Compostable packaging. Locally sourced ingredients.'
  },
  {
    id: '80',
    name: 'Raw Walnuts',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1614786972504-9bafb7b90730?w=600',
    category: 'Organic Food',
    description: 'Fresh, raw walnut halves. Great source of healthy fats.',
    co2Saved: 1.0,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    ingredients: ['Organic Walnuts'],
    sustainability: 'Orchards act as carbon sinks. Recyclable bag.'
  },
  // Sustainable Fashion Additions
  {
    id: '81',
    name: 'Organic Cotton T-Shirt',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1675239514439-1c128b0cffcd?w=600',
    category: 'Sustainable Fashion',
    description: 'Classic fit t-shirt made from 100% GOTS certified organic cotton.',
    co2Saved: 3.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['100% Organic Cotton'],
    sustainability: 'Saves 27 gallons of water compared to conventional cotton.'
  },
  {
    id: '82',
    name: 'Recycled Polyester Jacket',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1570836134706-61f60a36c57b?w=600',
    category: 'Sustainable Fashion',
    description: 'Water-resistant jacket made from 100% recycled polyester.',
    co2Saved: 7.2,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['Recycled Polyester'],
    sustainability: 'Keeps 20 plastic bottles out of landfills.'
  },
  {
    id: '83',
    name: 'Hemp Denim Jeans',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1694725369097-16efee947998?w=600',
    category: 'Sustainable Fashion',
    description: 'Durable jeans made from a hemp and organic cotton blend.',
    co2Saved: 5.8,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['55% Hemp', '45% Organic Cotton'],
    sustainability: 'Hemp requires 50% less water to grow than cotton.'
  },
  {
    id: '84',
    name: 'Vegan Leather Boots',
    price: 110.00,
    image: 'https://images.unsplash.com/photo-1581803361830-809a2d6d3815?w=600',
    category: 'Sustainable Fashion',
    description: 'Stylish boots made from high-quality apple leather.',
    co2Saved: 12.0,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Apple Skin Leather', 'Recycled Rubber Sole'],
    sustainability: 'Cruelty-free and reduces food waste.'
  },
  {
    id: '85',
    name: 'Bamboo Fiber Socks (3-Pack)',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1641482850218-7a2fed872551?w=600',
    category: 'Sustainable Fashion',
    description: 'Ultra-soft, breathable socks made from bamboo viscose.',
    co2Saved: 1.2,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['Bamboo Viscose', 'Recycled Nylon'],
    sustainability: 'Bamboo is naturally antibacterial and grows without pesticides.'
  },
  {
    id: '86',
    name: 'Linen Button-Down Shirt',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1519743670471-034311358429?w=600',
    category: 'Sustainable Fashion',
    description: 'Breathable and lightweight shirt made from 100% natural flax linen.',
    co2Saved: 2.8,
    isEco: true,
    condition: 'new',
    rating: 4.7,
    reviews: [],
    materials: ['100% Linen'],
    sustainability: 'Flax requires no irrigation and minimal chemicals.'
  },
  {
    id: '87',
    name: 'Sustainable Swimwear',
    price: 55.00,
    image: 'https://images.unsplash.com/photo-1631050165089-6311e0d6c5f3?w=600',
    category: 'Sustainable Fashion',
    description: 'Swimsuit made from ECONYL® regenerated nylon.',
    co2Saved: 4.5,
    isEco: true,
    condition: 'new',
    rating: 4.8,
    reviews: [],
    materials: ['ECONYL® Regenerated Nylon'],
    sustainability: 'Cleans up ocean waste like fishing nets.'
  },
  {
    id: '88',
    name: 'Cork Wallet',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1585401586477-2a671e1cae4e?w=600',
    category: 'Sustainable Fashion',
    description: 'Slim, durable wallet made from natural cork.',
    co2Saved: 1.5,
    isEco: true,
    condition: 'new',
    rating: 4.5,
    reviews: [],
    materials: ['Natural Cork'],
    sustainability: 'Cork oak trees are not cut down, only the bark is harvested.'
  },
  {
    id: '89',
    name: 'Organic Wool Sweater',
    price: 75.00,
    image: 'https://images.unsplash.com/photo-1696416686407-9fdc5d6146c7?w=600',
    category: 'Sustainable Fashion',
    description: 'Cozy sweater made from ethically sourced organic wool.',
    co2Saved: 8.0,
    isEco: true,
    condition: 'new',
    rating: 4.9,
    reviews: [],
    materials: ['Organic Wool'],
    sustainability: 'Biodegradable and renewable. Supports ethical animal farming.'
  },
  {
    id: '90',
    name: 'Recycled Sunglasses',
    price: 35.00,
    image: 'https://images.unsplash.com/photo-1738104955869-e32946fbd893?w=600',
    category: 'Sustainable Fashion',
    description: 'Sunglasses frames made from 100% recycled ocean plastic.',
    co2Saved: 1.0,
    isEco: true,
    condition: 'new',
    rating: 4.6,
    reviews: [],
    materials: ['Recycled Ocean Plastic'],
    sustainability: 'Helps clean our oceans one pair at a time.'
  }
];

export const testimonials = [
  {
    id: 't1',
    name: 'Jessica Thompson',
    role: 'Eco Advocate',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    comment: 'CircuCity has transformed how I shop. I love knowing exactly how much CO₂ I save with each purchase!',
    rating: 5
  },
  {
    id: 't2',
    name: 'David Chen',
    role: 'Sustainable Living Blogger',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    comment: 'The Eco Token rewards system is genius. It actually incentivizes sustainable choices.',
    rating: 5
  },
  {
    id: 't3',
    name: 'Maria Garcia',
    role: 'Green Consumer',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    comment: 'Quality products and fast shipping. Plus, I feel good about every purchase I make here.',
    rating: 5
  }
];
